title: Babis Kantouros # your name (or website title) here
logo: "viber_image_2021-12-06_22-20-14-007.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Assignments and script development within the framework of the corresponding university course.
  <br><br>
  <a href="www.linkedin.com/in/babis-kantouros">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
